# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dabwax
email: luizhrqas@gmail.com
description: > # 
  Full-stack web developer specialized in Software Engineer from Porto Alegre, Brazil.
  I have 6 years experience in web technologies and my preferred languages for work is Ruby and JavaScript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dabwax
github_username:  dabwax

# Build settings
markdown: kramdown
